const PENDINGKEY = 'mq-pending';
const DOINGKEY = 'mq-doing';
const ERRORKEY = 'mq-error';
const MQKEYJOIN = '||';
const ROOMCRAWLERNAME = 'crawler';
const ROOMCRUDNAME = 'crud';
const MQAUTO = 'MQAUTO';

const CHECKPENDSCHEDULESPE = '*/10 * * * * *';
const CHECKDOINGSCHEDULESPE = '0 * * * * *';
const HOURGETUPDATESCHEDULESPE = '0 0 1-23 * * *';
const ZEROPOINTSCHEDULESPE = '0 30 0 * * *';

module.exports = {
    PENDINGKEY,
    DOINGKEY,
    ERRORKEY,
    MQKEYJOIN,
    ROOMCRAWLERNAME,
    ROOMCRUDNAME,
    MQAUTO,
    CHECKPENDSCHEDULESPE,
    CHECKDOINGSCHEDULESPE,
    HOURGETUPDATESCHEDULESPE,
    ZEROPOINTSCHEDULESPE,
}